; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "AppHotel"
#define MyAppVersion "1.0"
#define MyAppPublisher "abarghou nadia"
#define MyAppExeName "ReservationHotel.exe"
#define MyAppAssocName MyAppName + ""
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{730CB6CF-9AD8-40D5-A62D-8225B71A5CFD}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=C:\Users\lenovo\Desktop\final
OutputBaseFilename=ReservationHotelSetupF
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "french"; MessagesFile: "compiler:Languages\French.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\lenovo\Documents\NetBeansProjects\appReservHotel\dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\lenovo\Documents\NetBeansProjects\appReservHotel\dist\appReservHotel.jar"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\lenovo\Documents\NetBeansProjects\appReservHotel\dist\lib\*"; DestDir: "{app}\lib"; Flags: ignoreversion recursesubdirs
Source: "C:\Users\lenovo\Documents\NetBeansProjects\appReservHotel\dist\lib\beansbinding-1.2.1.jar"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\lenovo\Documents\NetBeansProjects\appReservHotel\dist\lib\jcalendar-1.4.jar"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\lenovo\Documents\NetBeansProjects\appReservHotel\dist\lib\jcommon-1.0.22.jar"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\lenovo\Documents\NetBeansProjects\appReservHotel\dist\lib\jfreechart-1.0.19.jar"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\lenovo\Documents\NetBeansProjects\appReservHotel\dist\lib\mysql-connector-j-9.6.0.jar"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\lenovo\Documents\NetBeansProjects\appReservHotel\data\config.properties"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\lenovo\Documents\NetBeansProjects\appReservHotel\data\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\lenovo\Documents\NetBeansProjects\appReservHotel\src\config\config.properties"; DestDir: "{app}\config"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

