/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import controller.ChambreController;
import model.Chambre;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import main.BackgroundPanel;

/**
 *
 * @author lenovo
 */
public class ChambreForm extends javax.swing.JInternalFrame {

    private ChambreController chc;
    private DefaultTableModel model = null;
    private BackgroundPanel bg;

    public ChambreForm() {
        initComponents();
        chc = new ChambreController(this);
        model = (DefaultTableModel) tableChambre.getModel();
        loadChambre();

        tableChambre.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            int selectedRow = tableChambre.getSelectedRow();
            if(selectedRow != -1) {
                txtNumero.setText(tableChambre.getValueAt(selectedRow, 1).toString());
                txtType.setText(tableChambre.getValueAt(selectedRow, 2).toString());
                txtPrix.setText(tableChambre.getValueAt(selectedRow, 3).toString());
            }
        }
    });
        
       bg = new BackgroundPanel("/resources/c.jpg");
  
       this.setContentPane(bg);
        bg.setLayout(new java.awt.BorderLayout());
        bg.add(jPanel1, java.awt.BorderLayout.NORTH);
        bg.add(jScrollPane2, java.awt.BorderLayout.CENTER);
        jPanel1.setOpaque(false);
        jScrollPane2.setOpaque(false);
        jScrollPane2.getViewport().setOpaque(false); 


    }
    
    public void loadChambre(){
        model.setRowCount(0);
        for (Chambre ch : chc.getAll()) {
           model.addRow(new Object[]{
            ch.getId(),
            ch.getNumero(),
            ch.getType(),
            ch.getPrixParNuit()
            });
        
        }
    }
    
    private void clearForm() {
       txtNumero.setText("");
       txtType.setText("");
       txtPrix.setText("");
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtType = new javax.swing.JTextField();
        txtPrix = new javax.swing.JTextField();
        ajouter = new javax.swing.JButton();
        modifier = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableChambre = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestion des Chambres ");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Liste Des Chambres :"));
        jPanel1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Sans Serif Collection", 0, 24)); // NOI18N
        jLabel1.setText("Numero :");

        jLabel2.setFont(new java.awt.Font("Sans Serif Collection", 0, 24)); // NOI18N
        jLabel2.setText("Type    :");

        jLabel3.setFont(new java.awt.Font("Sans Serif Collection", 0, 24)); // NOI18N
        jLabel3.setText("Prix   :");

        ajouter.setBackground(new java.awt.Color(102, 204, 0));
        ajouter.setFont(new java.awt.Font("Sans Serif Collection", 0, 24)); // NOI18N
        ajouter.setText("Ajouter");
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });

        modifier.setBackground(new java.awt.Color(255, 255, 0));
        modifier.setFont(new java.awt.Font("Sans Serif Collection", 0, 24)); // NOI18N
        modifier.setText("Modifier ");
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });

        supprimer.setBackground(new java.awt.Color(255, 0, 51));
        supprimer.setFont(new java.awt.Font("Sans Serif Collection", 0, 24)); // NOI18N
        supprimer.setText("Supprimer");
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtType)
                            .addComponent(txtPrix)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addComponent(ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrix, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        tableChambre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Numero", "Type", "Prix Par Nuit"
            }
        ));
        jScrollPane2.setViewportView(tableChambre);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                .addGap(261, 261, 261))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
        try {
            int selectedRow = tableChambre.getSelectedRow();
            if(selectedRow == -1) {
                JOptionPane.showMessageDialog(null, "Sélectionnez une ligne pour modifier");
                return;
            }

            int id = Integer.parseInt(tableChambre.getValueAt(selectedRow, 0).toString());

            int numero = Integer.parseInt(txtNumero.getText());
            String type = txtType.getText();
            double prix = Double.parseDouble(txtPrix.getText());
            
            Chambre c = new Chambre();
            c.setId(id);
            c.setNumero(numero);
            c.setType(type);
            c.setPrixParNuit(prix);

            chc.update(c);

            loadChambre();
            clearForm();

            JOptionPane.showMessageDialog(null, "Chambre modifiée avec succès !");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Veuillez entrer des données valides");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur: " + e.getMessage());
        }
    }//GEN-LAST:event_modifierActionPerformed

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed

     try {
        int numero = Integer.parseInt(txtNumero.getText());
        String type = txtType.getText();
        double prix = Double.parseDouble(txtPrix.getText());

        Chambre c = new Chambre(numero, type, prix);
        chc.ajouter(c);

        loadChambre();
        clearForm();

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "les données que vous avez entrée est incorrect ");
    }
    }//GEN-LAST:event_ajouterActionPerformed

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        int ligne = tableChambre.getSelectedRow();
        if (ligne >= 0) {
            int id = (int) model.getValueAt(ligne, 0);
            int reponse = JOptionPane.showConfirmDialog(null, "Voulez-vous supprimer ?", "Confirmation", JOptionPane.YES_NO_OPTION);
            if (reponse == JOptionPane.YES_OPTION) {
                Chambre c = new Chambre(); 
                c.setId(id);
                new ChambreController(null).delete(c);
                loadChambre();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Sélectionnez une chambre !");
        }


    }//GEN-LAST:event_supprimerActionPerformed
   public JButton getAjouter() { return ajouter; }
   public JTable getTableChambre() { return tableChambre; }

   public JTextField getTxtNumero() { return txtNumero; }
   public JTextField getTxtType() { return txtType; }
   public JTextField getTxtPrix() { return txtPrix; }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton modifier;
    private javax.swing.JButton supprimer;
    private javax.swing.JTable tableChambre;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPrix;
    private javax.swing.JTextField txtType;
    // End of variables declaration//GEN-END:variables
}
