/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ChambreController;
import controller.ClientController;
import controller.ReservationController;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import main.BackgroundPanel;
import model.Chambre;
import model.Client;
import model.Reservation;

/**
 *
 * @author lenovo
 */
public class ReservationForm extends javax.swing.JInternalFrame {
    private ClientController cc;
    private ChambreController chc;
    private ReservationController rc;
    private DefaultTableModel model = null;
    private BackgroundPanel bg;
    

    
    public ReservationForm() {
        initComponents();
        cc = new ClientController(null);
        chc = new ChambreController(null);
        rc = new ReservationController(null);

        model = (DefaultTableModel) ResvTab.getModel();

        loadCombos();
        loadReservation();;

        bg = new BackgroundPanel("/resources/pic.png");
  
       this.setContentPane(bg);
        bg.setLayout(new java.awt.BorderLayout());
        bg.add(jPanel1, java.awt.BorderLayout.NORTH);
        bg.add(jPanel2, java.awt.BorderLayout.CENTER);
        jPanel1.setOpaque(false); 
        jPanel2.setOpaque(false); 
        
        ResvTab.setOpaque(false);
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);


        ResvTab.setDefaultRenderer(Object.class, new DefaultTableCellRenderer());

    }

    public void loadCombos() {
       IdClientComboBox.removeAllItems();
       IdChambreComboBox.removeAllItems();

        for (Client c : cc.getAll()) {
           IdClientComboBox.addItem(c);
        }

        for (Chambre ch : chc.getAll()) {
           IdChambreComboBox.addItem(ch);
        }
}

    public void loadReservation() {
    model.setRowCount(0);

    for (Reservation r : rc.getAll()) {
        model.addRow(new Object[]{
            r.getId(),
            r.getClientId(),
            r.getChambreId(),
            r.getDateDebut(),
            r.getDateFin()
        });
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        IdClientComboBox = new javax.swing.JComboBox();
        IdChambreComboBox = new javax.swing.JComboBox();
        dateDebut = new com.toedter.calendar.JDateChooser();
        dateFin = new com.toedter.calendar.JDateChooser();
        reserverBtn = new javax.swing.JButton();
        supprimerBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ResvTab = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Réservation");

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Sans Serif Collection", 0, 18)); // NOI18N
        jLabel1.setText("Client      :");

        jLabel2.setFont(new java.awt.Font("Sans Serif Collection", 0, 18)); // NOI18N
        jLabel2.setText("Chambre :");

        jLabel3.setFont(new java.awt.Font("Sans Serif Collection", 0, 18)); // NOI18N
        jLabel3.setText("Date début :");

        jLabel4.setFont(new java.awt.Font("Sans Serif Collection", 0, 18)); // NOI18N
        jLabel4.setText("Date Fin :");

        IdClientComboBox.setActionCommand("comboClient");
        IdClientComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdClientComboBoxActionPerformed(evt);
            }
        });

        IdChambreComboBox.setActionCommand("comboChambre");

        reserverBtn.setBackground(new java.awt.Color(51, 204, 0));
        reserverBtn.setFont(new java.awt.Font("Sans Serif Collection", 0, 18)); // NOI18N
        reserverBtn.setText("Réserver ");
        reserverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserverBtnActionPerformed(evt);
            }
        });

        supprimerBtn.setBackground(new java.awt.Color(255, 51, 51));
        supprimerBtn.setFont(new java.awt.Font("Sans Serif Collection", 0, 18)); // NOI18N
        supprimerBtn.setText("Supprimer");
        supprimerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dateFin, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                    .addComponent(dateDebut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IdChambreComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IdClientComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(104, 104, 104)
                .addComponent(reserverBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(supprimerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdClientComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reserverBtn)
                            .addComponent(supprimerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(IdChambreComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                            .addComponent(dateDebut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Liste de Réservation"));

        ResvTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Reservation", "Client ID", "Chambre ID", "Début", "Fin "
            }
        ));
        ResvTab.setOpaque(false);
        jScrollPane1.setViewportView(ResvTab);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reserverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserverBtnActionPerformed
        
        try {
        Chambre ch = (Chambre) IdChambreComboBox.getSelectedItem();
        Client cl = (Client) IdClientComboBox.getSelectedItem();

        if (ch == null || cl == null || dateDebut.getDate() == null || dateFin.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Remplissez tous les champs");
            return;
        }

        LocalDate debut = dateDebut.getDate().toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();

        LocalDate fin = dateFin.getDate().toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();

        rc.reserver(ch.getId(), cl.getId(), debut, fin);

        JOptionPane.showMessageDialog(this, "Réservation ajoutée");
        loadReservation();

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage());
    }
        
           
               
    }//GEN-LAST:event_reserverBtnActionPerformed

    private void supprimerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerBtnActionPerformed
        int ligne = ResvTab.getSelectedRow();

        if (ligne == -1) {
           JOptionPane.showMessageDialog(this, "Sélectionnez une réservation");
           return;
        }

        int id = Integer.parseInt(ResvTab.getValueAt(ligne, 0).toString());

        int rep = JOptionPane.showConfirmDialog(this, "Voulez-vous supprimer ?", "Confirmation",JOptionPane.YES_NO_OPTION);

    if (rep == JOptionPane.YES_OPTION) {
        Reservation r = new Reservation();
        r.setId(id);
        rc.delete(r);

        loadReservation();
    }
    }//GEN-LAST:event_supprimerBtnActionPerformed

    private void IdClientComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdClientComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdClientComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox IdChambreComboBox;
    private javax.swing.JComboBox IdClientComboBox;
    private javax.swing.JTable ResvTab;
    private com.toedter.calendar.JDateChooser dateDebut;
    private com.toedter.calendar.JDateChooser dateFin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton reserverBtn;
    private javax.swing.JButton supprimerBtn;
    // End of variables declaration//GEN-END:variables
}
